name: Output Information
run-name: Output Information
on: issues
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        # We are only interested in the event specific information on the github object
        run: echo "${{toJSON(github.event)}}"
